<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class BulkSellingFlowCodeType
{
    const C_BULKSIF_TO_CORE = 'BulkSIFToCore';
    const C_BULK_EDIT = 'BulkEdit';
    const C_BULK_EDITSIF = 'BulkEditSIF';
    const C_BULK_END_ITEMS = 'BulkEndItems';
    const C_BULK_RELIST = 'BulkRelist';
    const C_BULK_RELIST_ASSIF = 'BulkRelistAsSIF';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_EDIT_TEMPLATE = 'EditTemplate';
}
