<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class ReturnsRefundMethodCodeType
{
    const C_MONEY_BACK = 'MoneyBack';
    const C_MONEY_BACKOR_REPLACEMENT = 'MoneyBackorReplacement';
}
