<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class ReturnsDurationCodeType
{
    const C_DAYS_14 = 'Days_14';
    const C_DAYS_30 = 'Days_30';
    const C_DAYS_60 = 'Days_60';
}
