<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class Can:MoneyMovementTypeEnum
{
    const C_BUYER_PAYOUT = 'BUYER_PAYOUT';
    const C_PAYPAL_REFUND = 'PAYPAL_REFUND';
    const C_RECOUP_FROM_SELLER = 'RECOUP_FROM_SELLER';
    const C_SELLER_VOLUNTARY_REFUND = 'SELLER_VOLUNTARY_REFUND';
    const C_UNKNOWN = 'UNKNOWN';
}
