<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class CancelReasonEnum
{
    const C_ADDRESS_ISSUES = 'ADDRESS_ISSUES';
    const C_BUYER_ASKED_CANCEL = 'BUYER_ASKED_CANCEL';
    const C_BUYER_CANCEL_OR_ADDRESS_ISSUE = 'BUYER_CANCEL_OR_ADDRESS_ISSUE';
    const C_FOUND_CHEAPER_PRICE = 'FOUND_CHEAPER_PRICE';
    const C_ORDER_MISTAKE = 'ORDER_MISTAKE';
    const C_ORDER_UNPAID = 'ORDER_UNPAID';
    const C_OTHER = 'OTHER';
    const C_OUT_OF_STOCK_OR_CANNOT_FULFILL = 'OUT_OF_STOCK_OR_CANNOT_FULFILL';
    const C_PRICE_TOO_HIGH = 'PRICE_TOO_HIGH';
    const C_UNKNOWN = 'UNKNOWN';
    const C_WONT_ARRIVE_IN_TIME = 'WONT_ARRIVE_IN_TIME';
    const C_WRONG_PAYMENT_METHOD = 'WRONG_PAYMENT_METHOD';
    const C_WRONG_SHIPPING_ADDRESS = 'WRONG_SHIPPING_ADDRESS';
    const C_WRONG_SHIPPING_METHOD = 'WRONG_SHIPPING_METHOD';
}
