<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class FundingMethodTypeEnum
{
    const C_AVAILABLE_FUNDS = 'AVAILABLE_FUNDS';
    const C_CREDIT_CARD = 'CREDIT_CARD';
    const C_DIRECT_DEBIT = 'DIRECT_DEBIT';
    const C_PAY_UPON_INVOICE = 'PAY_UPON_INVOICE';
}
