<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class INRCreationReasonEnum
{
    const C_EMPTY_BOX = 'EMPTY_BOX';
    const C_INCOMPLETE_ORDER = 'INCOMPLETE_ORDER';
    const C_ITEM_NOT_RECEIVED_ASK_FOR_REFUND = 'ITEM_NOT_RECEIVED_ASK_FOR_REFUND';
    const C_ITEM_NOT_RECEIVED_TRACKING_SHOWS_DELIVERED = 'ITEM_NOT_RECEIVED_TRACKING_SHOWS_DELIVERED';
    const C_LATE_ORDER = 'LATE_ORDER';
    const C_TRACKING_INFO_UNAVAILABLE = 'TRACKING_INFO_UNAVAILABLE';
    const C_UNKNOWN = 'UNKNOWN';
}
