<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class PartialOrderTypeEnum
{
    const C_FULL_ORDER = 'FULL_ORDER';
    const C_PARTIAL_ORDER = 'PARTIAL_ORDER';
    const C_UNKNOWN = 'UNKNOWN';
}
