<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class RelistStatusEnum
{
    const C_FAILED = 'FAILED';
    const C_RELIST_ELIGIBLE = 'RELIST_ELIGIBLE';
    const C_SUCCESS = 'SUCCESS';
}
