<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class ReturnCountFilterEnum
{
    const C_ALL_OPEN = 'ALL_OPEN';
    const C_ALL_OPEN_REPLACEMENT = 'ALL_OPEN_REPLACEMENT';
    const C_ALL_OPEN_RETURN = 'ALL_OPEN_RETURN';
    const C_CLOSED = 'CLOSED';
    const C_EBAY_PLUS = 'EBAY_PLUS';
    const C_ITEM_DELIVERED = 'ITEM_DELIVERED';
    const C_ITEM_SHIPPED = 'ITEM_SHIPPED';
    const C_RETURN_STARTED = 'RETURN_STARTED';
    const C_SELLER_ACTION_DUE = 'SELLER_ACTION_DUE';
    const C_SELLER_ACTION_OVERDUE = 'SELLER_ACTION_OVERDUE';
    const C_SELLER_NO_ACTION = 'SELLER_NO_ACTION';
    const C_UNKNOWN = 'UNKNOWN';
}
