<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class ReturnReasonTypeEnum
{
    const C_CANCEL = 'CANCEL';
    const C_INSTORE = 'INSTORE';
    const C_REMORSE = 'REMORSE';
    const C_SNAD = 'SNAD';
    const C_UNKNOWN = 'UNKNOWN';
}
