<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class RlspTypeEnum
{
    const C_AU_PARCELPOINT = 'AU_PARCELPOINT';
    const C_AU_PARCELPOINT_AUPOST = 'AU_PARCELPOINT_AUPOST';
    const C_AU_PARCELPOINT_AUPOST_DROP = 'AU_PARCELPOINT_AUPOST_DROP';
    const C_AU_PARCELPOINT_COURIER_PICKUP = 'AU_PARCELPOINT_COURIER_PICKUP';
    const C_UNKNOWN = 'UNKNOWN';
}
