<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\PostOrder\Types;

use DTS\eBaySDK\PostOrder\Types\ProcessReturnRequestRestResponse;

class ProcessReturnRequestRestResponseTest extends \PHPUnit\Framework\TestCase
{
    private $obj;

    protected function setUp(): void
    {
        $this->obj = new ProcessReturnRequestRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\ProcessReturnRequestRestResponse', $this->obj);
    }

    public function testExtendsDecideReturnResponse()
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\DecideReturnResponse', $this->obj);
    }
}
