<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Types;

/**
 *
 * @property string $escalateReason
 * @property boolean $keepOriginalItem
 * @property \DTS\eBaySDK\PostOrder\Types\MoneyMovementRef $moneyMovementRef
 * @property \DTS\eBaySDK\PostOrder\Types\Amount $partialRefundAmount
 * @property \DTS\eBaySDK\PostOrder\Types\RefundDeductionType $refundDeductionType
 * @property string $rlspType
 * @property string $RMA
 * @property \DTS\eBaySDK\PostOrder\Types\ReturnAddressType $sellerReturnAddress
 * @property string $toEmailAddress
 * @property string $updatedTrackingNumber
 */
class ResponseHistoryAttributesType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'escalateReason' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'escalateReason'
        ],
        'keepOriginalItem' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'keepOriginalItem'
        ],
        'moneyMovementRef' => [
            'type' => 'DTS\eBaySDK\PostOrder\Types\MoneyMovementRef',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'moneyMovementRef'
        ],
        'partialRefundAmount' => [
            'type' => 'DTS\eBaySDK\PostOrder\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'partialRefundAmount'
        ],
        'refundDeductionType' => [
            'type' => 'DTS\eBaySDK\PostOrder\Types\RefundDeductionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'refundDeductionType'
        ],
        'rlspType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'rlspType'
        ],
        'RMA' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RMA'
        ],
        'sellerReturnAddress' => [
            'type' => 'DTS\eBaySDK\PostOrder\Types\ReturnAddressType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'sellerReturnAddress'
        ],
        'toEmailAddress' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'toEmailAddress'
        ],
        'updatedTrackingNumber' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'updatedTrackingNumber'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
