<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Types;

/**
 *
 * @property \DTS\eBaySDK\MerchantData\Types\ListingDurationDefinitionsType $ListingDurations
 * @property \DTS\eBaySDK\MerchantData\Types\ShippingTermRequiredDefinitionType $ShippingTermsRequired
 * @property \DTS\eBaySDK\MerchantData\Types\BestOfferEnabledDefinitionType $BestOfferEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\HomePageFeaturedEnabledDefinitionType $HomePageFeaturedEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ProPackEnabledDefinitionType $ProPackEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ValuePackEnabledDefinitionType $ValuePackEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ProPackPlusEnabledDefinitionType $ProPackPlusEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\AdFormatEnabledDefinitionType $AdFormatEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\BestOfferCounterEnabledDefinitionType $BestOfferCounterEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\BestOfferAutoDeclineEnabledDefinitionType $BestOfferAutoDeclineEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketSpecialitySubscriptionDefinitionType $LocalMarketSpecialitySubscription
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketRegularSubscriptionDefinitionType $LocalMarketRegularSubscription
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketPremiumSubscriptionDefinitionType $LocalMarketPremiumSubscription
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketNonSubscriptionDefinitionType $LocalMarketNonSubscription
 * @property \DTS\eBaySDK\MerchantData\Types\MinimumReservePriceDefinitionType $MinimumReservePrice
 * @property \DTS\eBaySDK\MerchantData\Types\TCREnabledDefinitionType $TransactionConfirmationRequestEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\SellerContactDetailsEnabledDefinitionType $SellerContactDetailsEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\SkypeMeTransactionalEnabledDefinitionType $SkypeMeTransactionalEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\SkypeMeNonTransactionalEnabledDefinitionType $SkypeMeNonTransactionalEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalListingDistancesRegularDefinitionType $LocalListingDistancesRegular
 * @property \DTS\eBaySDK\MerchantData\Types\LocalListingDistancesSpecialtyDefinitionType $LocalListingDistancesSpecialty
 * @property \DTS\eBaySDK\MerchantData\Types\LocalListingDistancesNonSubscriptionDefinitionType $LocalListingDistancesNonSubscription
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdPaymentMethodEnabledDefinitionType $ClassifiedAdPaymentMethodEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdShippingMethodEnabledDefinitionType $ClassifiedAdShippingMethodEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdBestOfferEnabledDefinitionType $ClassifiedAdBestOfferEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdCounterOfferEnabledDefinitionType $ClassifiedAdCounterOfferEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdAutoDeclineEnabledDefinitionType $ClassifiedAdAutoDeclineEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdContactByPhoneEnabledDefinitionType $ClassifiedAdContactByPhoneEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdContactByEmailEnabledDefintionType $ClassifiedAdContactByEmailEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\SafePaymentRequiredDefinitionType $SafePaymentRequired
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdPayPerLeadEnabledDefinitionType $ClassifiedAdPayPerLeadEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ItemSpecificsEnabledDefinitionType $ItemSpecificsEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\PaisaPayFullEscrowEnabledDefinitionType $PaisaPayFullEscrowEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\BrandMPNIdentifierEnabledDefinitionType $BrandMPNIdentifierEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\BestOfferAutoAcceptEnabledDefinitionType $BestOfferAutoAcceptEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdAutoAcceptEnabledDefinitionType $ClassifiedAdAutoAcceptEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\CrossBorderTradeNorthAmericaEnabledDefinitionType $CrossBorderTradeNorthAmericaEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\CrossBorderTradeGBEnabledDefinitionType $CrossBorderTradeGBEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\CrossBorderTradeAustraliaEnabledDefinitionType $CrossBorderTradeAustraliaEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\PayPalBuyerProtectionEnabledDefinitionType $PayPalBuyerProtectionEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\BuyerGuaranteeEnabledDefinitionType $BuyerGuaranteeEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ListingEnhancementDurationDefinitionType $GalleryFeaturedDurations
 * @property \DTS\eBaySDK\MerchantData\Types\INEscrowWorkflowTimelineDefinitionType $INEscrowWorkflowTimeline
 * @property \DTS\eBaySDK\MerchantData\Types\PayPalRequiredDefinitionType $PayPalRequired
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProAdFormatEnabledDefinitionType $eBayMotorsProAdFormatEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProContactByPhoneEnabledDefinitionType $eBayMotorsProContactByPhoneEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProPhoneCountDefinitionType $eBayMotorsProPhoneCount
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProContactByAddressEnabledDefinitionType $eBayMotorsProContactByAddressEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProStreetCountDefinitionType $eBayMotorsProStreetCount
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProCompanyNameEnabledDefinitionType $eBayMotorsProCompanyNameEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProContactByEmailEnabledDefinitionType $eBayMotorsProContactByEmailEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProBestOfferEnabledDefinitionType $eBayMotorsProBestOfferEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProAutoAcceptEnabledDefinitionType $eBayMotorsProAutoAcceptEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProAutoDeclineEnabledDefinitionType $eBayMotorsProAutoDeclineEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProPaymentMethodCheckOutEnabledDefinitionType $eBayMotorsProPaymentMethodCheckOutEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProShippingMethodEnabledDefinitionType $eBayMotorsProShippingMethodEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProCounterOfferEnabledDefinitionType $eBayMotorsProCounterOfferEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EBayMotorsProSellerContactDetailsEnabledDefinitionType $eBayMotorsProSellerContactDetailsEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketAdFormatEnabledDefinitionType $LocalMarketAdFormatEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketContactByPhoneEnabledDefinitionType $LocalMarketContactByPhoneEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketPhoneCountDefinitionType $LocalMarketPhoneCount
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketContactByAddressEnabledDefinitionType $LocalMarketContactByAddressEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketStreetCountDefinitionType $LocalMarketStreetCount
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketCompanyNameEnabledDefinitionType $LocalMarketCompanyNameEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketContactByEmailEnabledDefinitionType $LocalMarketContactByEmailEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketBestOfferEnabledDefinitionType $LocalMarketBestOfferEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketAutoAcceptEnabledDefinitionType $LocalMarketAutoAcceptEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketAutoDeclineEnabledDefinitionType $LocalMarketAutoDeclineEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketPaymentMethodCheckOutEnabledDefinitionType $LocalMarketPaymentMethodCheckOutEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketShippingMethodEnabledDefinitionType $LocalMarketShippingMethodEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketCounterOfferEnabledDefinitionType $LocalMarketCounterOfferEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\LocalMarketSellerContactDetailsEnabledDefinitionType $LocalMarketSellerContactDetailsEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdPhoneCountDefinitionType $ClassifiedAdPhoneCount
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdContactByAddressEnabledDefinitionType $ClassifiedAdContactByAddressEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdStreetCountDefinitionType $ClassifiedAdStreetCount
 * @property \DTS\eBaySDK\MerchantData\Types\ClassifiedAdCompanyNameEnabledDefinitionType $ClassifiedAdCompanyNameEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\SpecialitySubscriptionDefinitionType $SpecialitySubscription
 * @property \DTS\eBaySDK\MerchantData\Types\RegularSubscriptionDefinitionType $RegularSubscription
 * @property \DTS\eBaySDK\MerchantData\Types\PremiumSubscriptionDefinitionType $PremiumSubscription
 * @property \DTS\eBaySDK\MerchantData\Types\NonSubscriptionDefinitionType $NonSubscription
 * @property \DTS\eBaySDK\MerchantData\Types\ReturnPolicyEnabledDefinitionType $ReturnPolicyEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\HandlingTimeEnabledDefinitionType $HandlingTimeEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ReviseQuantityAllowedDefinitionType $ReviseQuantityAllowed
 * @property \DTS\eBaySDK\MerchantData\Types\RevisePriceAllowedDefinitionType $RevisePriceAllowed
 * @property \DTS\eBaySDK\MerchantData\Types\StoreOwnerExtendedListingDurationsEnabledDefinitionType $StoreOwnerExtendedListingDurationsEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\StoreOwnerExtendedListingDurationsDefinitionType $StoreOwnerExtendedListingDurations
 * @property \DTS\eBaySDK\MerchantData\Types\PaymentMethodDefinitionType $PaymentMethod
 * @property \DTS\eBaySDK\MerchantData\Types\Group1MaxFlatShippingCostDefinitionType $Group1MaxFlatShippingCost
 * @property \DTS\eBaySDK\MerchantData\Types\Group2MaxFlatShippingCostDefinitionType $Group2MaxFlatShippingCost
 * @property \DTS\eBaySDK\MerchantData\Types\Group3MaxFlatShippingCostDefinitionType $Group3MaxFlatShippingCost
 * @property \DTS\eBaySDK\MerchantData\Types\MaxFlatShippingCostCBTExemptDefinitionType $MaxFlatShippingCostCBTExempt
 * @property \DTS\eBaySDK\MerchantData\Types\MaxFlatShippingCostDefinitionType $MaxFlatShippingCost
 * @property \DTS\eBaySDK\MerchantData\Types\VariationsEnabledDefinitionType $VariationsEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\FreeGalleryPlusEnabledDefinitionType $FreeGalleryPlusEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\FreePicturePackEnabledDefinitionType $FreePicturePackEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ItemCompatibilityEnabledDefinitionType $ItemCompatibilityEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\MaxItemCompatibilityDefinitionType $MaxItemCompatibility
 * @property \DTS\eBaySDK\MerchantData\Types\MinItemCompatibilityDefinitionType $MinItemCompatibility
 * @property \DTS\eBaySDK\MerchantData\Types\ConditionEnabledDefinitionType $ConditionEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ConditionValuesDefinitionType $ConditionValues
 * @property \DTS\eBaySDK\MerchantData\Types\ValueCategoryDefinitionType $ValueCategory
 * @property \DTS\eBaySDK\MerchantData\Types\ProductCreationEnabledDefinitionType $ProductCreationEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EANEnabledDefinitionType $EANEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\ISBNEnabledDefinitionType $ISBNEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\UPCEnabledDefinitionType $UPCEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\CompatibleVehicleTypeDefinitionType $CompatibleVehicleType
 * @property \DTS\eBaySDK\MerchantData\Types\MaxGranularFitmentCountDefinitionType $MaxGranularFitmentCount
 * @property \DTS\eBaySDK\MerchantData\Types\ProfileCategoryGroupDefinitionType $ShippingProfileCategoryGroup
 * @property \DTS\eBaySDK\MerchantData\Types\ProfileCategoryGroupDefinitionType $PaymentProfileCategoryGroup
 * @property \DTS\eBaySDK\MerchantData\Types\ProfileCategoryGroupDefinitionType $ReturnPolicyProfileCategoryGroup
 * @property \DTS\eBaySDK\MerchantData\Types\VINSupportedDefinitionType $VINSupported
 * @property \DTS\eBaySDK\MerchantData\Types\VRMSupportedDefinitionType $VRMSupported
 * @property \DTS\eBaySDK\MerchantData\Types\SellerProvidedTitleSupportedDefinitionType $SellerProvidedTitleSupported
 * @property \DTS\eBaySDK\MerchantData\Types\DepositSupportedDefinitionType $DepositSupported
 * @property \DTS\eBaySDK\MerchantData\Types\GlobalShippingEnabledDefinitionType $GlobalShippingEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\AdditionalCompatibilityEnabledDefinitionType $AdditionalCompatibilityEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\PickupDropOffEnabledDefinitionType $PickupDropOffEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\DigitalGoodDeliveryEnabledDefinitionType $DigitalGoodDeliveryEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\EpidSupportedDefinitionType $EpidSupported
 * @property \DTS\eBaySDK\MerchantData\Types\KTypeSupportedDefinitionType $KTypeSupported
 * @property \DTS\eBaySDK\MerchantData\Types\ProductRequiredEnabledDefinitionType $ProductRequiredEnabled
 * @property \DTS\eBaySDK\MerchantData\Types\DomesticReturnsAcceptedDefinitionType $DomesticReturnsAcceptedValues
 * @property \DTS\eBaySDK\MerchantData\Types\InternationalReturnsAcceptedDefinitionType $InternationalReturnsAcceptedValues
 * @property \DTS\eBaySDK\MerchantData\Types\DomesticReturnsDurationDefinitionType $DomesticReturnsDurationValues
 * @property \DTS\eBaySDK\MerchantData\Types\InternationalReturnsDurationDefinitionType $InternationalReturnsDurationValues
 * @property \DTS\eBaySDK\MerchantData\Types\DomesticReturnsShipmentPayeeDefinitionType $DomesticReturnsShipmentPayeeValues
 * @property \DTS\eBaySDK\MerchantData\Types\InternationalReturnsShipmentPayeeDefinitionType $InternationalReturnsShipmentPayeeValues
 * @property \DTS\eBaySDK\MerchantData\Types\DomesticRefundMethodCodeType $DomesticRefundMethodValues
 * @property \DTS\eBaySDK\MerchantData\Types\InternationalRefundMethodCodeType $InternationalRefundMethodValues
 * @property \DTS\eBaySDK\MerchantData\Types\ReturnPolicyDescriptionEnabledDefinitionType $ReturnPolicyDescriptionEnabled
 */
class FeatureDefinitionsType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'ListingDurations' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ListingDurationDefinitionsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ListingDurations'
        ],
        'ShippingTermsRequired' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ShippingTermRequiredDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingTermsRequired'
        ],
        'BestOfferEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\BestOfferEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferEnabled'
        ],
        'HomePageFeaturedEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\HomePageFeaturedEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HomePageFeaturedEnabled'
        ],
        'ProPackEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ProPackEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProPackEnabled'
        ],
        'ValuePackEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ValuePackEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ValuePackEnabled'
        ],
        'ProPackPlusEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ProPackPlusEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProPackPlusEnabled'
        ],
        'AdFormatEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\AdFormatEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AdFormatEnabled'
        ],
        'BestOfferCounterEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\BestOfferCounterEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferCounterEnabled'
        ],
        'BestOfferAutoDeclineEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\BestOfferAutoDeclineEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferAutoDeclineEnabled'
        ],
        'LocalMarketSpecialitySubscription' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketSpecialitySubscriptionDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketSpecialitySubscription'
        ],
        'LocalMarketRegularSubscription' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketRegularSubscriptionDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketRegularSubscription'
        ],
        'LocalMarketPremiumSubscription' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketPremiumSubscriptionDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketPremiumSubscription'
        ],
        'LocalMarketNonSubscription' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketNonSubscriptionDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketNonSubscription'
        ],
        'MinimumReservePrice' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\MinimumReservePriceDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MinimumReservePrice'
        ],
        'TransactionConfirmationRequestEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\TCREnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TransactionConfirmationRequestEnabled'
        ],
        'SellerContactDetailsEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\SellerContactDetailsEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellerContactDetailsEnabled'
        ],
        'SkypeMeTransactionalEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\SkypeMeTransactionalEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SkypeMeTransactionalEnabled'
        ],
        'SkypeMeNonTransactionalEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\SkypeMeNonTransactionalEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SkypeMeNonTransactionalEnabled'
        ],
        'LocalListingDistancesRegular' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalListingDistancesRegularDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistancesRegular'
        ],
        'LocalListingDistancesSpecialty' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalListingDistancesSpecialtyDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistancesSpecialty'
        ],
        'LocalListingDistancesNonSubscription' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalListingDistancesNonSubscriptionDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalListingDistancesNonSubscription'
        ],
        'ClassifiedAdPaymentMethodEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdPaymentMethodEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdPaymentMethodEnabled'
        ],
        'ClassifiedAdShippingMethodEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdShippingMethodEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdShippingMethodEnabled'
        ],
        'ClassifiedAdBestOfferEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdBestOfferEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdBestOfferEnabled'
        ],
        'ClassifiedAdCounterOfferEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdCounterOfferEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdCounterOfferEnabled'
        ],
        'ClassifiedAdAutoDeclineEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdAutoDeclineEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdAutoDeclineEnabled'
        ],
        'ClassifiedAdContactByPhoneEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdContactByPhoneEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdContactByPhoneEnabled'
        ],
        'ClassifiedAdContactByEmailEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdContactByEmailEnabledDefintionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdContactByEmailEnabled'
        ],
        'SafePaymentRequired' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\SafePaymentRequiredDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SafePaymentRequired'
        ],
        'ClassifiedAdPayPerLeadEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdPayPerLeadEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdPayPerLeadEnabled'
        ],
        'ItemSpecificsEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ItemSpecificsEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ItemSpecificsEnabled'
        ],
        'PaisaPayFullEscrowEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\PaisaPayFullEscrowEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaisaPayFullEscrowEnabled'
        ],
        'BrandMPNIdentifierEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\BrandMPNIdentifierEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BrandMPNIdentifierEnabled'
        ],
        'BestOfferAutoAcceptEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\BestOfferAutoAcceptEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferAutoAcceptEnabled'
        ],
        'ClassifiedAdAutoAcceptEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdAutoAcceptEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdAutoAcceptEnabled'
        ],
        'CrossBorderTradeNorthAmericaEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\CrossBorderTradeNorthAmericaEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CrossBorderTradeNorthAmericaEnabled'
        ],
        'CrossBorderTradeGBEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\CrossBorderTradeGBEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CrossBorderTradeGBEnabled'
        ],
        'CrossBorderTradeAustraliaEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\CrossBorderTradeAustraliaEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CrossBorderTradeAustraliaEnabled'
        ],
        'PayPalBuyerProtectionEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\PayPalBuyerProtectionEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PayPalBuyerProtectionEnabled'
        ],
        'BuyerGuaranteeEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\BuyerGuaranteeEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BuyerGuaranteeEnabled'
        ],
        'GalleryFeaturedDurations' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ListingEnhancementDurationDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GalleryFeaturedDurations'
        ],
        'INEscrowWorkflowTimeline' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\INEscrowWorkflowTimelineDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'INEscrowWorkflowTimeline'
        ],
        'PayPalRequired' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\PayPalRequiredDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PayPalRequired'
        ],
        'eBayMotorsProAdFormatEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProAdFormatEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProAdFormatEnabled'
        ],
        'eBayMotorsProContactByPhoneEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProContactByPhoneEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProContactByPhoneEnabled'
        ],
        'eBayMotorsProPhoneCount' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProPhoneCountDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProPhoneCount'
        ],
        'eBayMotorsProContactByAddressEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProContactByAddressEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProContactByAddressEnabled'
        ],
        'eBayMotorsProStreetCount' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProStreetCountDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProStreetCount'
        ],
        'eBayMotorsProCompanyNameEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProCompanyNameEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProCompanyNameEnabled'
        ],
        'eBayMotorsProContactByEmailEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProContactByEmailEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProContactByEmailEnabled'
        ],
        'eBayMotorsProBestOfferEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProBestOfferEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProBestOfferEnabled'
        ],
        'eBayMotorsProAutoAcceptEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProAutoAcceptEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProAutoAcceptEnabled'
        ],
        'eBayMotorsProAutoDeclineEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProAutoDeclineEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProAutoDeclineEnabled'
        ],
        'eBayMotorsProPaymentMethodCheckOutEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProPaymentMethodCheckOutEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProPaymentMethodCheckOutEnabled'
        ],
        'eBayMotorsProShippingMethodEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProShippingMethodEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProShippingMethodEnabled'
        ],
        'eBayMotorsProCounterOfferEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProCounterOfferEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProCounterOfferEnabled'
        ],
        'eBayMotorsProSellerContactDetailsEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EBayMotorsProSellerContactDetailsEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayMotorsProSellerContactDetailsEnabled'
        ],
        'LocalMarketAdFormatEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketAdFormatEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketAdFormatEnabled'
        ],
        'LocalMarketContactByPhoneEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketContactByPhoneEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketContactByPhoneEnabled'
        ],
        'LocalMarketPhoneCount' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketPhoneCountDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketPhoneCount'
        ],
        'LocalMarketContactByAddressEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketContactByAddressEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketContactByAddressEnabled'
        ],
        'LocalMarketStreetCount' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketStreetCountDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketStreetCount'
        ],
        'LocalMarketCompanyNameEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketCompanyNameEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketCompanyNameEnabled'
        ],
        'LocalMarketContactByEmailEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketContactByEmailEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketContactByEmailEnabled'
        ],
        'LocalMarketBestOfferEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketBestOfferEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketBestOfferEnabled'
        ],
        'LocalMarketAutoAcceptEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketAutoAcceptEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketAutoAcceptEnabled'
        ],
        'LocalMarketAutoDeclineEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketAutoDeclineEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketAutoDeclineEnabled'
        ],
        'LocalMarketPaymentMethodCheckOutEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketPaymentMethodCheckOutEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketPaymentMethodCheckOutEnabled'
        ],
        'LocalMarketShippingMethodEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketShippingMethodEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketShippingMethodEnabled'
        ],
        'LocalMarketCounterOfferEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketCounterOfferEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketCounterOfferEnabled'
        ],
        'LocalMarketSellerContactDetailsEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\LocalMarketSellerContactDetailsEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LocalMarketSellerContactDetailsEnabled'
        ],
        'ClassifiedAdPhoneCount' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdPhoneCountDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdPhoneCount'
        ],
        'ClassifiedAdContactByAddressEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdContactByAddressEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdContactByAddressEnabled'
        ],
        'ClassifiedAdStreetCount' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdStreetCountDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdStreetCount'
        ],
        'ClassifiedAdCompanyNameEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ClassifiedAdCompanyNameEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ClassifiedAdCompanyNameEnabled'
        ],
        'SpecialitySubscription' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\SpecialitySubscriptionDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SpecialitySubscription'
        ],
        'RegularSubscription' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\RegularSubscriptionDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RegularSubscription'
        ],
        'PremiumSubscription' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\PremiumSubscriptionDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PremiumSubscription'
        ],
        'NonSubscription' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\NonSubscriptionDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'NonSubscription'
        ],
        'ReturnPolicyEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ReturnPolicyEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnPolicyEnabled'
        ],
        'HandlingTimeEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\HandlingTimeEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'HandlingTimeEnabled'
        ],
        'ReviseQuantityAllowed' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ReviseQuantityAllowedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReviseQuantityAllowed'
        ],
        'RevisePriceAllowed' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\RevisePriceAllowedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RevisePriceAllowed'
        ],
        'StoreOwnerExtendedListingDurationsEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\StoreOwnerExtendedListingDurationsEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'StoreOwnerExtendedListingDurationsEnabled'
        ],
        'StoreOwnerExtendedListingDurations' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\StoreOwnerExtendedListingDurationsDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'StoreOwnerExtendedListingDurations'
        ],
        'PaymentMethod' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\PaymentMethodDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentMethod'
        ],
        'Group1MaxFlatShippingCost' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\Group1MaxFlatShippingCostDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Group1MaxFlatShippingCost'
        ],
        'Group2MaxFlatShippingCost' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\Group2MaxFlatShippingCostDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Group2MaxFlatShippingCost'
        ],
        'Group3MaxFlatShippingCost' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\Group3MaxFlatShippingCostDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Group3MaxFlatShippingCost'
        ],
        'MaxFlatShippingCostCBTExempt' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\MaxFlatShippingCostCBTExemptDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxFlatShippingCostCBTExempt'
        ],
        'MaxFlatShippingCost' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\MaxFlatShippingCostDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxFlatShippingCost'
        ],
        'VariationsEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\VariationsEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VariationsEnabled'
        ],
        'FreeGalleryPlusEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\FreeGalleryPlusEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FreeGalleryPlusEnabled'
        ],
        'FreePicturePackEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\FreePicturePackEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FreePicturePackEnabled'
        ],
        'ItemCompatibilityEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ItemCompatibilityEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ItemCompatibilityEnabled'
        ],
        'MaxItemCompatibility' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\MaxItemCompatibilityDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxItemCompatibility'
        ],
        'MinItemCompatibility' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\MinItemCompatibilityDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MinItemCompatibility'
        ],
        'ConditionEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ConditionEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConditionEnabled'
        ],
        'ConditionValues' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ConditionValuesDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConditionValues'
        ],
        'ValueCategory' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ValueCategoryDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ValueCategory'
        ],
        'ProductCreationEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ProductCreationEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProductCreationEnabled'
        ],
        'EANEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EANEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EANEnabled'
        ],
        'ISBNEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ISBNEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ISBNEnabled'
        ],
        'UPCEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\UPCEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UPCEnabled'
        ],
        'CompatibleVehicleType' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\CompatibleVehicleTypeDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CompatibleVehicleType'
        ],
        'MaxGranularFitmentCount' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\MaxGranularFitmentCountDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MaxGranularFitmentCount'
        ],
        'ShippingProfileCategoryGroup' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ProfileCategoryGroupDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingProfileCategoryGroup'
        ],
        'PaymentProfileCategoryGroup' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ProfileCategoryGroupDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentProfileCategoryGroup'
        ],
        'ReturnPolicyProfileCategoryGroup' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ProfileCategoryGroupDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnPolicyProfileCategoryGroup'
        ],
        'VINSupported' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\VINSupportedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VINSupported'
        ],
        'VRMSupported' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\VRMSupportedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VRMSupported'
        ],
        'SellerProvidedTitleSupported' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\SellerProvidedTitleSupportedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellerProvidedTitleSupported'
        ],
        'DepositSupported' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\DepositSupportedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DepositSupported'
        ],
        'GlobalShippingEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\GlobalShippingEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GlobalShippingEnabled'
        ],
        'AdditionalCompatibilityEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\AdditionalCompatibilityEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AdditionalCompatibilityEnabled'
        ],
        'PickupDropOffEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\PickupDropOffEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PickupDropOffEnabled'
        ],
        'DigitalGoodDeliveryEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\DigitalGoodDeliveryEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DigitalGoodDeliveryEnabled'
        ],
        'EpidSupported' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EpidSupportedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EpidSupported'
        ],
        'KTypeSupported' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\KTypeSupportedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'KTypeSupported'
        ],
        'ProductRequiredEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ProductRequiredEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProductRequiredEnabled'
        ],
        'DomesticReturnsAcceptedValues' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\DomesticReturnsAcceptedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DomesticReturnsAcceptedValues'
        ],
        'InternationalReturnsAcceptedValues' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\InternationalReturnsAcceptedDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalReturnsAcceptedValues'
        ],
        'DomesticReturnsDurationValues' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\DomesticReturnsDurationDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DomesticReturnsDurationValues'
        ],
        'InternationalReturnsDurationValues' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\InternationalReturnsDurationDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalReturnsDurationValues'
        ],
        'DomesticReturnsShipmentPayeeValues' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\DomesticReturnsShipmentPayeeDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DomesticReturnsShipmentPayeeValues'
        ],
        'InternationalReturnsShipmentPayeeValues' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\InternationalReturnsShipmentPayeeDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalReturnsShipmentPayeeValues'
        ],
        'DomesticRefundMethodValues' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\DomesticRefundMethodCodeType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DomesticRefundMethodValues'
        ],
        'InternationalRefundMethodValues' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\InternationalRefundMethodCodeType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InternationalRefundMethodValues'
        ],
        'ReturnPolicyDescriptionEnabled' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ReturnPolicyDescriptionEnabledDefinitionType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnPolicyDescriptionEnabled'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
